-- Create Majors table
CREATE TABLE majors (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Exams table
CREATE TABLE exams (
  id TEXT PRIMARY KEY,
  subject TEXT NOT NULL,
  link TEXT NOT NULL,
  token TEXT NOT NULL,
  duration TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Exam Enrollments (Many-to-Many)
CREATE TABLE exam_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id TEXT REFERENCES exams(id) ON DELETE CASCADE,
  major_id TEXT REFERENCES majors(id) ON DELETE CASCADE,
  UNIQUE(exam_id, major_id)
);

-- Create Settings table (Single row)
CREATE TABLE settings (
  id TEXT PRIMARY KEY DEFAULT 'global',
  title TEXT NOT NULL,
  school_name TEXT NOT NULL,
  status TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert initial data
INSERT INTO settings (id, title, school_name, status)
VALUES ('global', 'Ujian Sekolah Utama 2026', 'SMK Negeri Digital', 'Aktif')
ON CONFLICT (id) DO NOTHING;

INSERT INTO majors (id, name) VALUES 
('tkj', 'Teknik Komputer & Jaringan'),
('rpl', 'Rekayasa Perangkat Lunak'),
('akl', 'Akuntansi'),
('otkp', 'Perkantoran')
ON CONFLICT (id) DO NOTHING;

INSERT INTO exams (id, subject, link, token, duration) VALUES 
('tkj-1', 'Dasar Desain Grafis', 'https://forms.google.com', 'DDG2026', '90'),
('tkj-2', 'Administrasi Sistem Jaringan', 'https://forms.google.com', 'ASJ2026', '120'),
('rpl-1', 'Pemrograman Berorientasi Objek', 'https://forms.google.com', 'PBO2026', '120'),
('rpl-2', 'Basis Data', 'https://forms.google.com', 'BD2026', '90')
ON CONFLICT (id) DO NOTHING;

INSERT INTO exam_enrollments (exam_id, major_id) VALUES
('tkj-1', 'tkj'),
('tkj-2', 'tkj'),
('rpl-1', 'rpl'),
('rpl-2', 'rpl')
ON CONFLICT DO NOTHING;

-- Enable Row Level Security (RLS)
-- For this demo, we can allow public read/write if needed, 
-- but normally you'd restrict this.
ALTER TABLE majors ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (adjust as needed for production)
CREATE POLICY "Allow public read access" ON majors FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON exams FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON exam_enrollments FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON settings FOR SELECT USING (true);

CREATE POLICY "Allow public all access" ON majors FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON exams FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON exam_enrollments FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON settings FOR ALL USING (true);
